/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    extend: {
      colors: {
        background: "#f9f9f9",
        primary: "#25160e",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed-variant": "#474835",
        "on-surface": "#1a1c1c",
        "on-background": "#1a1c1c",
        "secondary-container": "#e4e4ca",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-fixed-dim": "#c7c6c4",
        "tertiary-fixed": "#e3e2e0",
        "on-secondary-container": "#656651",
        "surface-container-low": "#f3f3f4",
        "on-primary-fixed-variant": "#574238",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#464745",
        "on-surface-variant": "#4f4540",
        "on-primary-fixed": "#281810",
        "on-primary-container": "#aa9084",
        "on-secondary-fixed": "#1b1d0d",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#dec1b3",
        "inverse-surface": "#2f3131",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#705a4f",
        "on-tertiary-fixed": "#1a1c1a",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        tertiary: "#181a18",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#dec1b3",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed": "#fbdcce",
        "on-tertiary-container": "#959593",
        "on-primary": "#ffffff",
        surface: "#f9f9f9",
        "tertiary-container": "#2d2e2c",
        "secondary-fixed-dim": "#c8c8af",
        "surface-variant": "#e2e2e2",
        "primary-container": "#3c2a21",
        "outline-variant": "#d3c3bd",
        outline: "#81756f",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e4e4ca",
        "on-error": "#ffffff",
        secondary: "#5f604b",
        "surface-container": "#eeeeee",
      },

      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },

      spacing: {
        "stack-lg": "48px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        gutter: "24px",
        "stack-sm": "12px",
        base: "8px",
        "margin-desktop": "64px",
        "stack-md": "24px",
      },

      fontFamily: {
        "label-md": ["Geist"],
        "body-lg": ["Geist"],
        "display-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "body-md": ["Geist"],
      },
    },
  },
  plugins: [],
}

